services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: my_database
    command: >
      bash -c "
      dockerize -wait tcp://db:3306 -timeout 20s &&
      php /var/www/html/scripts/init_db.php &&
      apache2-foreground
      "

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
